 _SCREEN.visible = .F.
 _SCREEN.windowstate = 1
 CLOSE ALL
 RELEASE ALL EXTENDED
 _SCREEN.icon = "ICONO.ICO"
 _SCREEN.caption = "Sistema de Productores Iancarina"
 _SCREEN.windowstate = 2
 _SCREEN.controlbox = .T.
 _SCREEN.closable = .F.
 _SCREEN.autocenter = .T.
 = CAPSLOCK(.T.)
 SET NULLDISPLAY TO '-'
 SET OPTIMIZE ON
 SET CPDIALOG OFF
 SET NOTIFY OFF
 SET ANSI ON
 SET ESCAPE OFF
 SET EXACT ON
 SET SAFETY OFF
 SET TALK OFF
 SET DATE british
 SET CENTURY ON
 SET DELETED ON
 SET STATUS BAR OFF
 SET SYSMENU TO
 SET SYSMENU AUTOMATIC
 SET EXCLUSIVE OFF
 SET CURRENCY TO ' Bs'
 SET CURRENCY RIGHT
 SET BELL OFF
 _SCREEN.visible = .T.
 SET REFRESH TO 5, 6
ENDPROC
**
